trigger:
- main

variables:
  dockerRegistryServiceConnection: 'docker-hub-connection' # Nombre de tu conexión de Docker Hub
  imageRepository: 'dessertapp' # Nombre del repositorio en Docker Hub
  containerRegistry: 'lordl' # Tu nombre de usuario en Docker Hub
  dockerfilePath: '**/Dockerfile' # Ruta del Dockerfile
  tag: 'latest'
  azureSubscription: 'Azure-Subscription' # Nombre de tu suscripción en Azure DevOps
  appServiceName: 'dessertapp-production' # Nombre de tu App Service
  resourceGroupName: 'MyResourceGroup' # Grupo de recursos

stages:
- stage: Build
  displayName: 'Build and Push Docker Image'
  jobs:
  - job: Build
    displayName: 'Build and Push'
    pool:
      name: 'WindowsPrivateAgent'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(containerRegistry)/$(imageRepository)
        command: 'buildAndPush'
        Dockerfile: $(dockerfilePath)
        tags: |
          $(tag)

- stage: Deploy
  displayName: 'Deploy to Azure App Service'
  jobs:
  - job: Deploy
    displayName: 'Deploy to App Service'
    pool:
      name: 'WindowsPrivateAgent'
    steps:
    - task: AzureWebAppContainer@1
      inputs:
        azureSubscription: $(azureSubscription)
        appName: $(appServiceName)
        resourceGroupName: $(resourceGroupName)
        deployToSlotOrASE: true
        imageName: $(containerRegistry)/$(imageRepository):$(tag)
