trigger:
  - main

variables:
  containerRegistry: 'docker.io'
  imageRepository: 'jhonl2002/dessertapp'
  tag: 'latest'
  azureSubscription: 'Azure-Subscription'
  appServiceName: 'dessert-app-jhonl2002'
  resourceGroupName: 'DessertApp'

stages:
  - stage: BuildAndPush
    displayName: 'Build and Push Docker Image'
    jobs:
      - job: Build
        displayName: 'Build and Push Docker Image'
        pool:
          name: 'WindowsPrivateAgent'
        steps:
          - task: DockerCompose@1
            displayName: 'Build Docker Image'
            inputs:
              dockerComposeFile: '**/docker-compose.prod.yml'
              action: 'Build services'
              additionalImageTags: $(tag)

          - task: DockerCompose@1
            displayName: 'Push Docker Image to Docker Hub'
            inputs:
              dockerComposeFile: '**/docker-compose.prod.yml'
              action: 'Push services'
              additionalImageTags: $(tag)

  - stage: Deploy
    displayName: 'Deploy to Azure App Service'
    dependsOn: BuildAndPush
    jobs:
      - job: Deploy
        displayName: 'Deploy to App Service'
        pool:
          name: 'WindowsPrivateAgent'
        steps:
          - task: AzureWebAppContainer@1
            inputs:
              azureSubscription: $(azureSubscription)
              appName: $(appServiceName)
              resourceGroupName: $(resourceGroupName)
              imageName: 'docker.io/$(imageRepository):$(tag)'
