trigger:
- main

stages:
- stage: Build
  displayName: 'Build and Push Docker Image'
  jobs:
  - job: Build
    displayName: 'Build and Push'
    pool:
      name: 'WindowsPrivateAgent'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(containerRegistry)/$(imageRepository)
        command: 'buildAndPush'
        Dockerfile: $(dockerfilePath)
        tags: |
          $(tag)

- stage: Deploy
  displayName: 'Deploy to Azure App Service'
  jobs:
  - job: Deploy
    displayName: 'Deploy to App Service'
    pool:
      name: 'WindowsPrivateAgent'
    steps:
    - task: AzureWebAppContainer@1
      inputs:
        azureSubscription: $(azureSubscription)
        appName: $(appServiceName)
        resourceGroupName: $(resourceGroupName)
        deployToSlotOrASE: true
        imageName: $(containerRegistry)/$(imageRepository):$(tag)
