trigger:
  - main

variables:
  containerRegistry: 'docker.io'
  imageRepository: 'jhonl2002/dessertapp'
  tag: 'latest'
  azureSubscription: 'Azure-Subscription'
  appServiceName: 'dessert-app-jhonl2002'
  resourceGroupName: 'DessertApp'

stages:
  - stage: Deploy
    displayName: 'Deploy to Azure App Service'
    jobs:
      - job: Deploy
        displayName: 'Deploy to App Service'
        pool:
          name: 'WindowsPrivateAgent'
        steps:
          - task: AzureWebAppContainer@1
            inputs:
              azureSubscription: $(azureSubscription)
              appName: $(appServiceName)
              resourceGroupName: $(resourceGroupName)
              imageName: 'docker.io/$(imageRepository):$(tag)'
