services:
  dessertapp:
    image: jhonl2002/dessertapp:latest
    container_name: dessertapp-production
    build:
      context: .
      dockerfile: DessertApp/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "8080:8080"
  

